# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-03-25 09:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('name', models.CharField(max_length=255)),
                ('tell', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('drivingLicence', models.ImageField(upload_to='')),
                ('carImage', models.ImageField(upload_to='')),
                ('certificateOfIdentificationImage', models.ImageField(upload_to='')),
                ('headPortrait', models.ImageField(upload_to='')),
                ('points', models.IntegerField()),
                ('mark', models.IntegerField()),
                ('vehicleType', models.CharField(max_length=30)),
                ('orderNum', models.IntegerField()),
                ('msg', models.TextField()),
                ('driversLicence', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Msg',
            fields=[
                ('tell', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('msgTime', models.DateField()),
                ('msgFrom', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transportTime', models.TimeField()),
                ('start', models.CharField(max_length=100)),
                ('startDetail', models.CharField(max_length=100)),
                ('end', models.CharField(max_length=100)),
                ('endDetail', models.CharField(max_length=100)),
                ('anZhuang', models.NullBooleanField()),
                ('huiDan', models.NullBooleanField()),
                ('banYun', models.NullBooleanField()),
                ('payment', models.IntegerField()),
                ('orderStatus', models.CharField(max_length=50)),
                ('additionalDemand', models.CharField(max_length=50)),
                ('remarks', models.CharField(max_length=300)),
                ('vehicleType', models.CharField(max_length=30)),
                ('pay', models.IntegerField()),
                ('driverId', models.CharField(max_length=11)),
                ('userId', models.CharField(max_length=11)),
                ('evaluation', models.CharField(max_length=300)),
                ('mark', models.IntegerField()),
                ('orderTime', models.TimeField()),
                ('recevingTime', models.TimeField()),
                ('finishTime', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('tell', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('myDriver', models.IntegerField()),
                ('points', models.IntegerField()),
                ('password', models.CharField(max_length=16)),
            ],
        ),
    ]
