# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-03-26 06:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20170325_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='additionalDemand',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='contactsName',
            field=models.CharField(blank=True, max_length=11),
        ),
        migrations.AlterField(
            model_name='order',
            name='contactsTell',
            field=models.CharField(blank=True, max_length=11),
        ),
        migrations.AlterField(
            model_name='order',
            name='driverId',
            field=models.CharField(blank=True, max_length=11),
        ),
        migrations.AlterField(
            model_name='order',
            name='evaluation',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='order',
            name='finishTime',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='mark',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='orderStatus',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='orderTime',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='recevingTime',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='remarks',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='order',
            name='transportTime',
            field=models.TimeField(blank=True),
        ),
    ]
