# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-03-26 07:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20170326_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='orderTime',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
