# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-03-26 07:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20170326_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='transportTime',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
