# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-03-27 06:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20170326_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='licensePlateNumber',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='anZhuang',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='banYun',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='huiDan',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
