# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-03-27 07:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20170327_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='carImage',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='driver',
            name='certificateOfIdentificationImage',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='driver',
            name='driversLicence',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='driver',
            name='drivingLicence',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='driver',
            name='headPortrait',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='driver',
            name='mark',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='msg',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='orderNum',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='points',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='vehicleType',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
