# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-03-29 17:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20170329_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='finishTime',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='recevingTime',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
