# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-03-30 02:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20170329_1754'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='carImage',
        ),
        migrations.AddField(
            model_name='order',
            name='serviceTime',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
