# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-03-30 02:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20170330_0207'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='password',
            field=models.CharField(default=1234, max_length=16),
            preserve_default=False,
        ),
    ]
