# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-03-31 05:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_driver_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='pay',
            field=models.CharField(blank=True, max_length=11),
        ),
    ]
