# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-03-31 06:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20170331_0538'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='status',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
