# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-01-16 17:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testtable',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
