# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-02-24 14:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_auto_20170117_0116'),
    ]

    operations = [
        migrations.AddField(
            model_name='testtable',
            name='image',
            field=models.ImageField(blank=True, upload_to='/image/'),
        ),
    ]
