# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-03-13 17:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0003_testtable_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testtable',
            name='image',
            field=models.ImageField(blank=True, upload_to='image/'),
        ),
    ]
